### ISSUE TITLE
zerodivisionerror

### ISSUE THREAD

**Issue by CzxWbFamily** [KAIST-VCLAB/EgocentricReconstruction#15]
run the demo, but face this error

node num:  7241632
upload node num: 0 / 7241631
Start update
End update
download num: 0 / 7241631
Update Done
Enumerating...
Number of triangles 0
loading     9
generating  16
updating    13
enumerating 3
stl save    0
Texture mapping
Save bbox rendering trajectory
Save scaled rendering trajectory
/data/S221000776-CZX/.conda/envs/egocentric/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
INFO:root:[main] Loading mesh from ./demo/mesh/sponza/mesh.stl ...
INFO:root:[main] configuration:
  - video_name:                       sponza
  - stl_name:                         mesh
  - face_n:                           0
  - texture_map_max_sizeK:            10.0
  - texture_map_min_triangle_side:    7
  - total_video_frames_count:         200
  - frame_idx_list:                   [10, 180, 90, 60, 100, 150, 70, 170, 120, 190, 80, 110, 160, 50, 30, 20, 130, 0, 40, 140]

INFO:root:    elapsed time (0. Initialize): 0.40 sec
Traceback (most recent call last):
  File "/data/S221000776-CZX/D2L/EgocentricReconstruction/main.py", line 46, in <module>
    main()
  File "/data/S221000776-CZX/D2L/EgocentricReconstruction/main.py", line 43, in main
    texture_util.run_texture(config)
  File "/data/S221000776-CZX/D2L/EgocentricReconstruction/utils/texture_util.py", line 28, in run_texture
    texture_main.main(texture_args)
  File "/data/S221000776-CZX/D2L/EgocentricReconstruction/texture_mapping/texture_main.py", line 122, in main
    texture_main_single_texture_map.main(args)
  File "/data/S221000776-CZX/D2L/EgocentricReconstruction/texture_mapping/texture_main_single_texture_map.py", line 78, in main
    tiler = EqtriangleTiler(texture_map_max_sizeK=texture_map_max_sizeK,
  File "/data/S221000776-CZX/D2L/EgocentricReconstruction/texture_mapping/equitriangle_tiler.py", line 16, in __init__
    self.N = np.ceil(self.face_n / self.M)
ZeroDivisionError: division by zero

which step may have problem.
thank you

**Comment by Hyeonjoong-Jang** [comment]
It seems like the mesh was not generated properly.
Can you check if the depth maps for each frame was estimated correctly?
