### ISSUE TITLE
When no good pairs found --> no exr file --> "ValueError: Unsupported dtype object"

### ISSUE THREAD

**Issue by ResonancePA** [KAIST-VCLAB/EgocentricReconstruction#7]
During the depth calculation, if no good pairs found, there would be no exr file generated, and this would cause a cupy value error (since no file would be read in, the input would be a NONE type.
The solution might be generate a new video without those frames, but I wonder if there is a better way.
Thanks!

**Comment by ResonancePA** [comment]
The details are put here:

/content/EgocentricReconstruction/demo/depth/sponza_depth/108.exr exists
first_idx: 109
No good pairs found
/content/EgocentricReconstruction/demo/depth/sponza_depth/110.exr exists
/content/EgocentricReconstruction/demo/depth/sponza_depth/111.exr exists
/content/EgocentricReconstruction/demo/depth/sponza_depth/112.exr exists

/usr/local/lib/python3.8/dist-packages/cupy/_creation/from_data.py:76: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return _core.array(a, dtype, False, order)
Traceback (most recent call last):
  File "/content/EgocentricReconstruction/main.py", line 48, in <module>
    main()
  File "/content/EgocentricReconstruction/main.py", line 35, in main
    weight_util.run_weight(config)
  File "/content/EgocentricReconstruction/utils/weight_util.py", line 248, in run_weight
    depth_maps = video_util.get_all_depths(depth_path, len(video_frame_rt))
  File "/content/EgocentricReconstruction/utils/video_util.py", line 61, in get_all_depths
    return cp.asarray(depth_list)
  File "/usr/local/lib/python3.8/dist-packages/cupy/_creation/from_data.py", line 76, in asarray
    return _core.array(a, dtype, False, order)
  File "cupy/_core/core.pyx", line 2357, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2381, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2509, in cupy._core.core._array_default
ValueError: Unsupported dtype objec

**Comment by ResonancePA** [comment]
Sorry, this method doesn't work very well. After deleting the frames, there would be more frame that has no good pairs.

**Comment by ResonancePA** [comment]
Thanks!

**Comment by Hyeonjoong-Jang** [comment]
Closing
